### ISSUE TITLE
Shell Completion not appearing in palette

### ISSUE THREAD

**Issue by vdesabou** [yamaton/vscode-h2o#7]
Using latest version of extension, I don't see any commands starting with "Shell Completion" when I use VSCode palette, likle explained in https://github.com/yamaton/vscode-h2o#supported-commands

Is there anything missing ?

**Comment by yamaton** [comment]
"Shell Completion" shows up in Command Palette **only when the active window is "Shell Script" mode**. So, would you try again after opening a shell script file?

**Comment by vdesabou** [comment]
Oh yes, that is perfectly working when I'm on a .sh script.
Suggestion: maybe you could add a note on that in the README, as it was not obvious and thought for months that it was not working :)

**Comment by yamaton** [comment]
Will do.
