### ISSUE TITLE
How to add our own json file ?

### ISSUE THREAD

**Issue by vdesabou** [yamaton/vscode-h2o#9]
I'm using a CLI for my project [here](https://kafka-docker-playground.io/#/cli?id=playground)
I've managed to create a [YAML](https://github.com/vdesabou/kafka-docker-playground/blob/master/scripts/cli/playground.yaml)/[JSON](https://github.com/vdesabou/kafka-docker-playground/blob/master/scripts/cli/playground.json) that is working fine with your extension.

However, in order to run it, I have to add this json to generic.json.gz and hack catchFetcher.js to download that gz file instead of yours:

```
    fetchAllCurated(kind = 'general', isForcing = false) {
        return __awaiter(this, void 0, void 0, function* () {
            console.log("[CacheFetcher.fetchAllCurated] Started running...");
            const url = `https://github.com/vdesabou/kafka-docker-playground/raw/master/scripts/cli/general.json.gz`;
```

I'm wondering if there could be a better way to do that ?
Any thoughts ?

**Comment by yamaton** [comment]
Current implementation can load individual JSON via "Shell Completion: Load Command Spec (experimental)". It loads matching JSON if available here: https://github.com/yamaton/h2o-curated-data/tree/main/experimental/json

So, if you are okay to do some hack, please overwrite the `url` in `downloadCommandToCache` to point to your JSON location like you did. It's a bit simpler.

Another quick and easy solution is to add your command spec to  https://github.com/yamaton/h2o-curated-data. I'm open to any solutions.

**Comment by vdesabou** [comment]
I used the experimental trick, working like a charm!

Thanks 😊
